spring.application.name=pfmea-backend

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/pfmea_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JWT
# ===============================
jwt.secret=7f3c9a2d1e5b8a6c4d9e1f7b3a8c2d6e5f1a9b7c4d2e8f6a3c5b9d1e7f2a4c8
jwt.expiration=86400000

# ===============================
# SERVER
# ===============================
server.port=8080